USE [master]
GO

/****** Object:  Database [Tea-Collection]    Script Date: 8/14/2021 3:17:30 PM ******/
CREATE DATABASE [Tea-Collection]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Tea-Collection', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Tea-Collection.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Tea-Collection_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Tea-Collection_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tea-Collection].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tea-Collection] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tea-Collection] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tea-Collection] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tea-Collection] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tea-Collection] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tea-Collection] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tea-Collection] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tea-Collection] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tea-Collection] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tea-Collection] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tea-Collection] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tea-Collection] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tea-Collection] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tea-Collection] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tea-Collection] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tea-Collection] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tea-Collection] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tea-Collection] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tea-Collection] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tea-Collection] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tea-Collection] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tea-Collection] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tea-Collection] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tea-Collection] SET  MULTI_USER 
GO

ALTER DATABASE [Tea-Collection] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tea-Collection] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tea-Collection] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tea-Collection] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Tea-Collection] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Tea-Collection] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Tea-Collection] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Tea-Collection] SET  READ_WRITE 
GO

